routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/blog/category/{slug?}', 'BlogController@category')->name('category');
Route::get('/blog/article/{slug?}', 'BlogController@article')->name('article');
Route::post('/blog/article/{slug?}/comments', 'Admin\CommentController@store')->name('newComment');

Route::group(['prefix'=>'admin', 'namespace'=>'Admin', 'middleware'=>['auth']], function(){
	Route::get('/','DashboardController@dashboard')->name('admin.index');
	Route::resource('/category', 'CategoryController', ['as'=>'admin']);
	Route::resource('/article', 'ArticleController', ['as'=>'admin']);
	Route::resource('/comment', 'CommentController', ['as'=>'admin']);
	


});

Route::get('/', function () {
    return view('blog.home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
     public function article()
    {
        return $this->belongsTo('App\Article');
    }
    public function scopeLastComments($query, $count)
    {
        return $query->orderBy('created_at', 'desc')->take($count)->get();
    }
}

app/Http/Controllers/Admin/CommentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Comment;
use App\Article;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CommentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.comments.index', [
            'comments' => Comment::orderBy('created_at', 'desc')->paginate(10)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request,$slug)
    {
        $article = Article::where('slug', $slug)->first();

            $comment = new Comment();

            $comment->comment = $request->comment;
            $comment->approved = false;
            $comment->article_id = $article->id;

            $comment->save();

            return redirect()->route('article', $slug);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function show(Comment $comment)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function edit(Comment $comment)
    {
        return view('admin.comments.edit', [
            'comment' => $comment
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Comment $comment)
    {
        $comment->comment = $request['comment'];
        $comment->approved = $request['approved'];
        $comment->save();

        return redirect()->route('admin.comment.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function destroy(Comment $comment)
    {
        $comment->delete();

        return redirect()->route('admin.comment.index');
    }
}

resources/views/admin/comments/edit.blade.php
@extends('admin.layouts.app_admin')

@section('content')

    <div class="container">

        @component('admin.components.breadcrumb')
            @slot('title') Comment appending @endslot
            @slot('parent') Home @endslot
            @slot('active') Comments @endslot
        @endcomponent
        <hr/>

        <form class="form-horizontal" action="{{route('admin.comment.update', $comment)}}" method="post">
            {{ csrf_field() }}
            <input type="hidden" name="_method" value="put">
            {{-- Form include--}}
            @include('admin.comments.partials.form')

        </form>
    </div>

@endsection

resources/views/admin/comments/index.blade.php
@extends('admin.layouts.app_admin')

@section('content')

    <div class="container">
        @component('admin.components.breadcrumb')
            @slot('title') Комменты @endslot
            @slot('parent') Главная @endslot
            @slot('active') Комменты @endslot
        @endcomponent

        <table class="table table-striped">
            <thead>
            <th>Коммент</th>
            <th>Пойдет ли коммент ?</th>
            <th class="text-right">Действие</th>
            </thead>
            <tbody>
            @forelse($comments as $comment)
                <tr>
                    <td>{{$comment->comment}}</td>
                    <td>{{$comment->approved}}</td>
                    <td class="text-right">
                        <form onsubmit="if(confirm('Удалить ?')){return true}else{return false}"
                              action="{{route('admin.comment.destroy', $comment)}}" method="post">
                            {{ method_field('DELETE') }}
                            {{csrf_field()}}

                            <a class="btn btn-default" href="{{route('admin.comment.edit', $comment)}}">
                                Редактировать
                            </a>

                            <button type="submit" class="btn">Удалить</button>
                        </form>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="3" class="text-center"><h2>Данные отсутствуют</h2></td>
                </tr>
            @endforelse
            </tbody>
            <tfoot>
            <tr>
                <td colspan="3">
                    <ul class="pagination pull-right">
                        {{$comments->links()}}
                    </ul>
                </td>
            </tr>
            </tfoot>
        </table>
    </div>

@endsection